---
title: "SYS 3060: A01"
author: "Rahul Sunilkumar"
date: today
format: 
  pdf:
    pdf-engine: pdflatex
    fontfamily: newtxtext
header-includes:
  - \usepackage{newtxmath}
  - \usepackage{xcolor}
  - \definecolor{blu}{RGB}{40,40,120}
--- 

# Question 1

A student will run experiments in a lab session. With a probability of 0.5, the student will have enough time to run only one experiment, and with a probability of 0.5, the student will have enough time to run two experiments. Each experiment will fail with probability 0.3, independently of the other experiments.

### \textcolor{blu}{(a) Find the probability that the student succeeds in all experiments during a lab session.}

If they run one experiment, that one must succeed. If they run two experiments, *both* must succeed. 

*Case 1:* Each experiment fails with probability $0.3$, so succeeds with $0.7$. This happens with probability $0.5$ meaning this case contributes $0.5 \times 0.7$.

*Case 2:* The two experiments succeed *independently* with probability $0.7$. This situation happens with probability $0.5$ contributing $0.5 * 0.7^2$.

```{python}
#| echo: false
ans =  0.5*0.7 + 0.5*0.7**2
```

Thus, the probability that the student succeeds in all experiments is `{python} ans`.

\hfill $\square$

### \textcolor{blu}{(b) Find the probability that exactly one experiment fails.}

```{python}
#| echo: true
ans =  0.5*0.3 + 0.5*(0.3*0.7 + 0.7*0.3)
```

Using a case by case deconstruction similar to (a), we get `{python} ans`. 

\hfill $\square$

### \textcolor{blu}{(c) Find the probability that the student performs two experiments and both succeed.}

```{python}
#| echo: true
0.5 * (0.7 * 0.7)
```

\hfill $\square$

### \textcolor{blu}{(d) Given that the first experiment succeeds, find the probability that the second experiment fails.}

Due to the independence, $$P(\text{second fails} \mid \text{first succeeds}) = P(\text{second fails}) = 0.3 $$

\hfill $\square$

### \textcolor{blu}{(e) Find the expected number of successful experiments in a lab session.}

In Case 1, the expectation of $X$ given that there is only one experiment is $0.7$ as given. For cae 2, it would be $0.7 + 0.7 = 1.4$. Thus we get 

```{python}
#| echo: true
ans = 0.5*0.7 + 0.5*1.4
```

which yields `{python} ans`. Which makes sense because on average the student runs 1.5 experiments and $0.5 \times 0.7 = 1.05$.

\hfill $\square$

### \textcolor{blu}{(f) Find the variance of the number of experiments the student runs in a lab session.}

Define $N$ to be the *number of experiments run in a lab session*, where $N=1$ with half probabiliy and $N=2$ with half probability.

We know that $$E(N) = 1(0.5) + 2(0.5) = 0.5 + 1 = 1.5,$$ which is a fact we used in the previous part as well.

Similarly we can also conclude that $$E(N^2) = 1(0.5) + 4(0.5) = 2.5.$$

Thus, $$\text{Var}(N) = E(N^2)- (E(N))^2$$ which is 0.25.

\hfill $\square$

# Question 2

A lab sensor detects particles. The time $X$ (in minutes) until the nexxt detection is exponential with rate $\lambda$. 

### \textcolor{blu}{(a) Find the time $\tau$ such that there is 75\% chance that the sensor detects a particle by time $\tau$.}

We are told that $X \sim \text{Exponential}$ for which we know the CDF to be $$P(X \leq t) = 1 - e^{-\lambda t}, \quad t \geq 0.$$ We just want to solve for $$1 - e^{\lambda \tau} = 0.75$$
Which yields the following answer:
$$
\begin{aligned}
e^{-\lambda t} &= 0.25 \\
-\lambda\tau &= \ln(0.25) \\
\tau &= -\ln(0.25)/\lambda \\
\tau &= \ln(4)/\lambda
\end{aligned}
$$

\hfill $\square$

### \textcolor{blu}{(b) Find the probability that the waiting time until the next particle detection exceeds 5 minutes.}

We want $P(X > 5) = e^{-5\lambda}$. That's the answer.

\hfill $\square$

### \textcolor{blu}{(c) Find the probability that a particle is detected between the next 5 to 8 minutes.}

$P(5 < X < 8) = (1-e^{-8\lambda}) - (1-e)^{-5\lambda} = e^{-5\lambda} - e^{-8\lambda}.$

\hfill $\square$

### \textcolor{blu}{(d) Given that the detection occured in the first ten minutes, find the probability that another detection occurs within the next 2 minutes.}

Given that the exponential distribution is memoryless, the future waiting time does not depend on when the previous detection occurred. So the answer is just $$1-e^{-2\lambda}.$$

\hfill $\square$

### \textcolor{blu}{(e) Find the expected waiting time until the next particle is detected and its variance, consider $\lambda = 0.1$ detections/minute.}

Well the expectation and variance are described by $$\mathbb E(X) = 1/\lambda, \quad \mathbb V(X) = 1/\lambda^2.$$ This gives us answers, 10 minutes and 100 minutes$^2$, respectively.

\hfill $\square$

# Question 3
Students arrive at a shuttle top according to a Poisson process with rate $$\lambda = \text{ 6 students per hour.}$$
Each arriving student is an undergraduate with probability 0.7 and a graduate with probability 0.3, independently of everything else.
Let $N(t)$be the total number of arrivals in the firt $t$ hours. Let $N_U(t)$ and $N_G(t)$ be the numbers of undergraduates and graduates arriving in the first $t$ hours.

### \textcolor{blu}{(a) Compute $P(N(0.5) = 2)$.}

For $N(t) \sim \text{Poisson}(\lambda t)$, $$\lambda t = 6 \times 0.5 = 3 \implies N(0.5) \sim \text{Poisson}(3).$$

We know that $$P(N = k) = \frac{\mu^k e^{-\mu}}{k!}$$ which when $k=2$ and $\mu = 3$ are subbed in, we get $$P(N(0.5) = 2) = 4.5e^{-3}.$$

\hfill $\square$

### \textcolor{blu}{(b) Compute $P(N_U(1) = 3 \text{ and } N_G(1) = 1)$.}

Because the two counts are independent of each other, we can say: $$P(N_U(1) = 3 \cap N_G(1) = 1) = P(N_U(1) = 3) \cdot P(N_G(1) = 1).$$

Just compute both and multiply.

```{python}
import math

lambda_u = 4.2   # UG/hour
lambda_g = 1.8   # G/hour

# Probabilities
p_u = (lambda_u**3 * math.exp(-lambda_u)) / math.factorial(3)
p_g = (lambda_g**1 * math.exp(-lambda_g)) / math.factorial(1)

p = p_u * p_g
```

By hand I arrived to $(4.2^3)(1.8)(e^{-6})/3!$ which does match our computed answer of `{python} p`. 

\hfill $\square$

### \textcolor{blu}{(c) Given that $N(1)=4$, compute the probability that exactly 3 of them are undergradutes.}

So here we are just looking at total count, the Poisson distribution doesn't matter because we are classifying four independent arrivals. Given $N(1) = 4$ we know $$N_U(1) \mid N(1) = 4 \sim \text{Bin}(4, 0.7).$$ We want to know $P(N_U(1) = 3 \mid N(1) = 4)$ which is simply $${4 \choose 3}(0.7)^3(0.3)^1$$ which is `{python} math.comb(4,3)*(0.7**3)*(0.3)**1`.

\hfill $\square$

# Question 4

A device experiences failures over time. The number of failures observed up to time $t$ is modeled by a non-homogeneous Poisson process (NHPP) $\{N(t), t \geq 0\}$ with time-varying rate $$\lambda(t) = 3e^{-t}, \quad t \geq 0,$$ where $t$ is measured by days and $\lambda(t)$ has units of failures per day. Let $N(t)$ denote the total number of failures that occur in the same time interval $[0,t]$. 

Let $T_1$ denote the time of the first failure: $$T_1 = \inf\{t\geq 0 \mid N(t) \geq 1\}.$$ Recall that the CDF of $T_1$ is defined as $$F_{T_1}(t) = P(T_1 \geq t), \quad t \geq 0,$$ which represents the probability that the first failure occurs by time $t$. *Hint: You may ue the NHPP mean value function* $$\Lambda(t) = \int_0^t \lambda(s)ds.$$

### \textcolor{blu}{(a) Compute the probability of no failures occur during the interval $[0,2]$, i.e., compute $P(N(2) = 0)$.}

$$\Lambda(t) = \int_0^t \lambda(s)ds$$
So $P(N(t) = 0) = \exp(-\Lambda(t))$ where $\lambda(t) = 3e^{-t}$, so $$\Lambda(2) = \int_0^2 3e^{-s}ds = 3(1-e^{-2}).$$ Therefore, $$P(N(2) = 0) = \exp(-3(1-e^{-2})).$$ In decimal form this is `{python} math.exp(-3*(1-math.e**-2))`.

\hfill $\square$

### \textcolor{blu}{(b) Derive an explicit expression for the CDF of $T_1$, i.e., find $F_{T_1}(t) = P(T_1 \geq t)$ for $t \geq 0$.}

The event *the first failure happens after time $t$* is the same as *no failures occur by time $t$* which is denoted: $\{T_1 > t\} \iff \{N(t) = 0\}$. 

Similar to above we derive that $$P(T_1 > t) = \exp(-3(1-e^{-t})).$$ And, we know the actual form of a CDF is $P(T_1 \geq t)$ in the situation, yielding $$P(T_1 \geq t) = 1-\exp(-3(1-e^{-t})).$$ Small change to do it with the other sign.

\hfill $\square$

### \textcolor{blu}{(c) Compute $P(T_1 > 1)$, the probability that the first failure occurs after day 1.}

We already have $P(T_1 > t) = \exp(-3(1-e^{-1}))$, so with $t=1$ we get `{python} math.exp(-3*(1-math.e**-1))`.

\hfill $\square$